[workspace]
members = [
    "crates/fennec",
    "crates/fennec-parser",
    "xtask",
]
resolver = "2"

[profile.dev]
debug = 0

[profile.release]
debug = 0

[profile.release-lto]
inherits = "release"
lto = "thin"

[workspace.package]
version = "0.1.1"
authors = ["Gregory Petrosyan <pgregory@pgregory.net>"]
homepage = "https://github.com/fennec-lang/fennec"
repository = "https://github.com/fennec-lang/fennec"
license = "MPL-2.0"
edition = "2021"

[workspace.dependencies]
ansi_term = "0.12"
anyhow = "1.0"
env_logger = "0.10"
lalrpop = { version = "0.19.8", default-features = false, features = ["lexer"]}
lalrpop-util = { version = "0.19.8", default-features = false, features = ["std", "lexer"]}
log = "0.4"
regex = "1"
rustyline = { version = "10.0", default-features = false }
xflags = "0.3.1"

fennec-parser = { path = "crates/fennec-parser" }

