[workspace]
members = ["crates/*", "xtask"]
resolver = "2"

[profile.dev]
debug = 0

[profile.release]
debug = 0

[profile.release-lto]
inherits = "release"
lto = "thin"

[workspace.package]
version = "0.1.3"
description = "Fennec is an experimental programming language and environment"
authors = ["Gregory Petrosyan <pgregory@pgregory.net>"]
homepage = "https://github.com/fennec-lang/fennec"
repository = "https://github.com/fennec-lang/fennec"
license = "MPL-2.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0"
env_logger = "0.10"
lalrpop = { version = "0.20", default-features = false, features = ["lexer", "unicode"] }
lalrpop-util = { version = "0.20", default-features = false, features = ["lexer", "unicode"] }
log = { version = "0.4", features = ["kv_unstable"] }
regex = "1"
time = { version = "0.3.22", default-features = false, features = ["local-offset", "formatting", "parsing"] }
xflags = "0.3.1"
xshell = "0.2.3"

fennec-parser = { path = "crates/fennec-parser", version = "0.1.3" }

[workspace.metadata.release]
allow-branch = ["master"]
shared-version = true
tag-name = "v{{version}}"
tag-message = "fennec v{{version}}"
pre-release-commit-message = "fennec v{{version}}"
