[package]
name = "fennec"
description = "Fennec is an experimental programming language and environment"
version = "0.1.1"
authors = ["Gregory Petrosyan <pgregory@pgregory.net>"]
homepage = "https://github.com/fennec-lang/fennec"
repository = "https://github.com/fennec-lang/fennec"
readme = "README.md"
license = "MPL-2.0"
edition = "2021"

[[bin]]
path = "crates/fc/main.rs"
name = "fc"

[dependencies]
ansi_term = "0.12"
anyhow = "1.0"
env_logger = "0.9"
log = "0.4"
rustyline = { version = "10.0", default-features = false }

[workspace]
members = [
]
