[workspace]
members = [
    "crates/fennec-parser",
]

[workspace.package]
version = "0.1.1"
authors = ["Gregory Petrosyan <pgregory@pgregory.net>"]
homepage = "https://github.com/fennec-lang/fennec"
repository = "https://github.com/fennec-lang/fennec"
license = "MPL-2.0"
edition = "2021"

[workspace.dependencies]
ansi_term = "0.12"
anyhow = "1.0"
env_logger = "0.9"
lalrpop = { version = "0.19.8", default-features = false, features = ["lexer"]}
lalrpop-util = { version = "0.19.8", default-features = false, features = ["std", "lexer"]}
log = "0.4"
regex = "1"
rustyline = { version = "10.0", default-features = false }
xflags = "0.3.1"

fennec-parser = { path = "crates/fennec-parser" }

[package]
name = "fennec"
description = "Fennec is an experimental programming language and environment"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
readme = "README.md"
build = "crates/fc/build.rs"

[[bin]]
path = "crates/fc/main.rs"
name = "fc"

[dependencies]
ansi_term.workspace = true
anyhow.workspace = true
env_logger.workspace = true
log.workspace = true
rustyline.workspace = true
xflags.workspace = true
fennec-parser.workspace = true

[build-dependencies]
anyhow.workspace = true
