[package]
name = "fennec"
description = "Fennec is an experimental programming language and environment"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
readme = "README.md"
default-run = "fc"

[[bin]]
path = "src/main.rs"
name = "fc"

[dependencies]
ansi_term.workspace = true
anyhow.workspace = true
env_logger.workspace = true
log.workspace = true
rustyline.workspace = true
xflags.workspace = true
fennec-parser.workspace = true

[build-dependencies]
anyhow.workspace = true
