[package]
name = "fennec"
version.workspace = true
description.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
readme = "../../README.md"
default-run = "fennec"

[dependencies]
ansi_term.workspace = true
anyhow.workspace = true
env_logger.workspace = true
log.workspace = true
rustyline.workspace = true
xflags.workspace = true
fennec-parser.workspace = true

[build-dependencies]
anyhow.workspace = true
