[package]
name = "fennec-vfs"
version.workspace = true
description.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
readme = false

[dependencies]
anyhow.workspace = true
parking_lot.workspace = true

fennec-common.workspace = true
