[package]
name = "xtask"
version = "0.0.0"
license.workspace = true
edition.workspace = true
readme = false
publish = false

[dependencies]
anyhow.workspace = true
xflags.workspace = true

[package.metadata.release]
release = false
